Endpoints
Tashydaije/LocalLibrary pull request #20
Opened 2021-07-18 01:37 UTC by Tashydaije

2021-07-19 05:41 UTC, pmutua commented on v1/serializers.py
> +    BookInstance,
looks good nothing here to change

2021-07-19 05:41 UTC, pmutua commented on v1/serializers.py
> +        fields = '__all__'
serializer looks good nothing here to change

2021-07-19 05:42 UTC, pmutua commented on v1/urls.py
> +    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
urls look good nothing here to change

2021-07-19 05:42 UTC, pmutua commented on v1/views.py
> +    BookInstanceSerializer,
looks good nothing here to change

2021-07-19 05:46 UTC, pmutua requested changes
Hi Natasha, please check some of the comments I added in this code review

2021-07-19 05:46 UTC, pmutua commented on v1/views.py
> +        return BookInstance.objects.filter(borrower=user, status__exact='o').order_by('due_back')
You have hardcoded the filtering of book instaces by status, could we remove the harcoded section and make it more dynamic. Do you know a way we could achieve this?

2021-07-19 05:46 UTC, pmutua commented on v1/views.py
> +    queryset = BookInstance.objects.filter(status__exact='o')
Hi Natasha, lets remove the hard coded filtering of status. You are filtering book instances by status 'o' suppose we want to filter by any other status how can we make this dynamic?

2021-07-19 06:00 UTC, pmutua requested changes

2021-07-19 06:00 UTC, pmutua commented on v1/views.py
> +    serializer_class = AuthorSerializer
This view has been correctly implemented. Do you know of any other way we can implement this instead of using the `generics.RetrieveUpdateDestroyAPIView` which is doing everything for you on the fly (this is usually used when you have a basic view there is a situation you have to implement your custom view which has some complex functionality you would want to achieve? Lets use `APIView` base class and create  your custom `GET`, `PUT` and `DELETE` methods.

2021-07-19 06:12 UTC, merged

2021-07-22 11:07 UTC, Tashydaije commented on v1/views.py
> +    serializer_class = AuthorSerializer
I've implemented the view using the APIView base class, kindly check

2021-07-23 09:29 UTC, pmutua commented on v1/views.py
> +    serializer_class = AuthorSerializer
Have you done any pull request for the changes ?